### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LRAnimations** [Cedgetec/SchulinfoApp#59]
Ist aufgetreten, als ich mich vom GG ausgeloggt habe und dann in die SWS eingeloggt habe.

```
11-23 13:09:19.019 31705-31705/de.gebatzens.sia E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: de.gebatzens.sia, PID: 31705
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.view.PagerAdapter android.support.v4.view.ViewPager.getAdapter()' on a null object reference
                                                                      at de.gebatzens.sia.view.GGSwipeLayout.onInterceptTouchEvent(GGSwipeLayout.java:96)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                      at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                      at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                  	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver
```

**Comment by Gebatzens** [comment]
Might be fixed in 6d1297e6e4b31a9d5f0aa08af3d1d9d9de69f400
