### ISSUE TITLE
Exception Message

### ISSUE THREAD

**Issue by LRAnimations** [Cedgetec/SchulinfoApp#65]
```
01-17 20:04:38.726 12024-12024/de.gebatzens.sia E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: de.gebatzens.sia, PID: 12024
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{de.gebatzens.sia/de.gebatzens.sia.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
                                                                      at de.gebatzens.sia.fragment.RemoteDataFragment.onViewCreated(RemoteDataFragment.java:208)
                                                                      at de.gebatzens.sia.fragment.SubstFragment.onViewCreated(SubstFragment.java:81)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                      at android.app.Activity.performStart(Activity.java:6268)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by Gebatzens** [comment]
Wann passiert das denn??

**Comment by Gebatzens** [comment]
Fixed in 999a6df3779f50eba6e69c6a91a47a5c45251303
